### ISSUE TITLE
fn_fuzzy with ida pro 7.4

### ISSUE THREAD

**Issue by jimmy0435** [TakahiroHaruyama/ida_haru#2]
Thanks for providing good tool.

I encountered some problems with using fn_fuzzy in ida pro 7.4.
I tried to fix it but fail.

In the beginning, I change some function names because IDA changes some function names.
(1)NextHead -> next_head
(2)GetMnem -> print_insn_mnem

Then, it shows the message below. I have no idea how to fix it.

```
C:\Users\analysis\Desktop\ida plugin\fn_fuzzy\fn_fuzzy.py: in method 'get_tinfo', argument 1 of type 'tinfo_t *'
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.4\python\2\ida_idaapi.py", line 619, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Users/analysis/Desktop/ida plugin/fn_fuzzy/fn_fuzzy.py", line 608, in <module>
    main()
  File "C:/Users/analysis/Desktop/ida plugin/fn_fuzzy/fn_fuzzy.py", line 593, in main
    ff.export()
  File "C:/Users/analysis/Desktop/ida plugin/fn_fuzzy/fn_fuzzy.py", line 452, in export
    idaapi.get_tinfo(fva, tinfo)
  File "C:\Program Files\IDA Pro 7.4\python\2\ida_nalt.py", line 2339, in get_tinfo
    return _ida_nalt.get_tinfo(*args)
TypeError: in method 'get_tinfo', argument 1 of type 'tinfo_t *'
```

**Comment by TakahiroHaruyama** [comment]
On IDA 7.4, the setting for backward compatibility in idapython.cfg is disabled by default.

AUTOIMPORT_COMPAT_IDA695 = NO

For now, please enable the option then the code should work. 
I'll rewrite it when the option is permanently disabled ;-)
